### ISSUE TITLE
REPL task

### ISSUE THREAD

**Issue by emlyn** [hyPiRion/inlein#8]
I had a go at creating a task that starts a repl (I hadn't noticed [this](https://github.com/hyPiRion/inlein/blob/master/examples/repl.clj) when I started). It also takes an optional list of dependencies on the command line (in maven group:artifact:version format, because that's easier to type on the command line), so you can easily start a repl with arbitrary dependencies loaded on the classpath, e.g.: `inlein --repl --deps org.clojure:clojure:1.8.0,something:else:0.1.0`

What do you think? My code is [here](https://github.com/emlyn/inlein/compare/master...repl)

One drawback is that it will by default pull in Clojure 1.4.0 (from REPLy) if you don't specify another version. It would be nice if it defaulted to the latest stable version.

**Comment by hyPiRion** [comment]
Oh, this idea looks neat!

I think the code itself looks alright, but we should probably separate the namespaces into the different tasks we add into inlein, just to clean it up a bit. And I think I would add a new endpoint (e.g. named `"repl-opts" or `"repl-jvm-opts"`) instead of piggybacking onto `"jvm-opts"`, but I haven't looked too much into the code yet.

Are there any issues in using, say, `group/artifact:version`? I guess it could leave the false impression that the group is a directory and the artifact is some file in that directory, but I think it otherwise would be fine?

And re latest version: While I don't like unreproducible builds or scripts, I guess it's alright for repls. We could use version ranges, like `[org.clojure/clojure "[1.8.0,2.0)]"`, to specify the "latest" Clojure version.

**Comment by emlyn** [comment]
I don't mind `group/artifact:version` if you prefer, but I think `group:artifact:version` might be slightly more "standard" (see https://maven.apache.org/pom.html#Maven_Coordinates)? Although I'm not completely convinced that this is better than lein-style deps because it prevents you from specifying `:exclusions`.

I think defaulting to latest Clojure version is OK for repls, the current implementation is not much more stable - it just takes whatever REPLy happens to pull in by default. Another option would be to require the user to specify a version, and not pull in any by default (might make it easier for using alternative implementations like Jaunt), or better, specify it in a config file in `~/.inlein`, along with other things like more deps, injections etc. for the repl.

**Comment by hyPiRion** [comment]
Ah, I wasn't aware it was a common notation. I think making it similar to dependency vectors would be nice, but I don't have strong opinions on it.

I was also thinking about artifacts where the group and artifact name are identical – e.g. clj-time or reply. It would be convenient to let `reply:0.3.7` expand to `reply:reply:0.3.7`.

I'll try to clean up the daemon internals today and get back to this.

**Comment by hyPiRion** [comment]
Solved by #24.
